/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet_l3;

import java.awt.Color;

/**
 *
 * @author Amine
 */
public class Message extends javax.swing.JFrame {
    
    Utilisateur utilisateur;
    String dataMessage;
    String dateMessage; // type à modifier
    StatutMessage statutMessage;
    String statutMessageTxt;
    
    Color couleur_txt;
    Color couleur_background;
    
    String statutMessageChemin;

    /**
     * Creates new form Message
     * @param utilisateur
     * @param dataMessage
     * @param dateMessage
     * @param statutMessage
     */
    public Message(Utilisateur utilisateur, String dataMessage, String dateMessage,StatutMessage statutMessage) {
        this.utilisateur=utilisateur;
        this.dataMessage=dataMessage;
        this.dateMessage=dateMessage; // type à modifier
        this.statutMessage=statutMessage;
        
        
        // on changera certainement ce switch qui est "statique", et on le remplacera par des show/hide d'icones, ce sera + propre
        switch (statutMessage){
            case nonRecuServeur :
                this.statutMessageTxt="Non reçu par le serveur.";
                this.statutMessageChemin="/projet_l3/img/statutMessage_nonRecuServeur.png";
                break;                
            case nonRecuUtilisateurs :
                this.statutMessageTxt="Non reçu par tous les utilisateurs.";
                this.statutMessageChemin="/projet_l3/img/statutMessage_nonRecuUtilisateurs.png";
                break;
            case nonLu :
                this.statutMessageTxt="Non lu par tous les utilisateurs.";
                this.statutMessageChemin="/projet_l3/img/statutMessage_nonLu.png";
                break;
            case lu :
                this.statutMessageTxt="Lu par tous les utilisateurs.";
                this.statutMessageChemin="/projet_l3/img/statutMessage_lu.png";
                break;
            default : this.statutMessageTxt="Erreur !";

        }
        
        // faire le test proprement pour mettre les bonnes couleurs aux messages
        
        // c'est lui
        if(utilisateur.identifiantUtilisateur.equals("bnm1931a")){
            couleur_txt=new java.awt.Color(255, 255, 255);
            couleur_background=new java.awt.Color(188, 7, 46);
        }else{ // c'est les autres
            couleur_txt=new java.awt.Color(28, 28, 28);
            couleur_background=new java.awt.Color(235, 235, 235);
        }
        
        

        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txt_dataMessage = new javax.swing.JTextArea();
        footer = new javax.swing.JPanel();
        lbl_dateMessage = new javax.swing.JLabel();
        pnl_statutMessage = new javax.swing.JPanel();
        lbl_statutMessage = new javax.swing.JLabel();
        lbl_statutMessageImg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_nomUtilisateur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel3.setBackground(this.couleur_background);

        jPanel1.setBackground(this.couleur_background);
        jPanel1.setLayout(new java.awt.BorderLayout());

        txt_dataMessage.setEditable(false);
        txt_dataMessage.setBackground(this.couleur_background);
        txt_dataMessage.setColumns(20);
        txt_dataMessage.setFont(new java.awt.Font("Titillium", 0, 12)); // NOI18N
        txt_dataMessage.setForeground(this.couleur_txt);
        txt_dataMessage.setRows(5);
        txt_dataMessage.setText(this.dataMessage);
        txt_dataMessage.setBorder(null);
        txt_dataMessage.setFocusable(false);
        jPanel1.add(txt_dataMessage, java.awt.BorderLayout.CENTER);

        footer.setBackground(this.couleur_background);
        footer.setLayout(new java.awt.GridLayout(1, 2));

        lbl_dateMessage.setFont(new java.awt.Font("Titillium", 0, 10)); // NOI18N
        lbl_dateMessage.setForeground(this.couleur_txt);
        lbl_dateMessage.setText(this.dateMessage);
        footer.add(lbl_dateMessage);

        pnl_statutMessage.setBackground(this.couleur_background);
        pnl_statutMessage.setLayout(new java.awt.BorderLayout());

        lbl_statutMessage.setFont(new java.awt.Font("Titillium", 0, 10)); // NOI18N
        lbl_statutMessage.setForeground(this.couleur_txt);
        lbl_statutMessage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_statutMessage.setText(this.statutMessageTxt);
        pnl_statutMessage.add(lbl_statutMessage, java.awt.BorderLayout.CENTER);

        lbl_statutMessageImg.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.statutMessageChemin)));
        lbl_statutMessageImg.setToolTipText(this.statutMessageTxt);
        pnl_statutMessage.add(lbl_statutMessageImg, java.awt.BorderLayout.LINE_END);

        footer.add(pnl_statutMessage);

        jPanel1.add(footer, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(this.couleur_background);
        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        lbl_nomUtilisateur.setFont(new java.awt.Font("Titillium Lt", 1, 14)); // NOI18N
        lbl_nomUtilisateur.setForeground(this.couleur_txt);
        lbl_nomUtilisateur.setText(this.utilisateur.getNom()+" "+this.utilisateur.getPrenom());
        jPanel2.add(lbl_nomUtilisateur);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(jPanel1);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Utilisateur amine=new Utilisateur("bnm1931a", "aminemdp", "BENZERGA", "Amine");
                Utilisateur gauthier=new Utilisateur("bjg97f", "gauthiermdp", "BOUYJOU", "Gauthier");
                new Message(amine, "Gros probleme !!! en salle de TP de Java. Venez viiiiite","Dimanche 3 décembre, 14:12", StatutMessage.nonRecuUtilisateurs ).setVisible(true);
                new Message(gauthier, "Bonjour, nous avons bien reçu votre demande. Nous arrivons !!! ","Dimanche 3 décembre, 14:26", StatutMessage.lu ).setVisible(true);
                new Message(amine, "Merci de votre aide :-)","Dimanche 3 décembre, 14:52", StatutMessage.nonLu ).setVisible(true);
                new Message(gauthier, "Le plaisir est pour nous ! ","Dimanche 3 décembre, 14:59", StatutMessage.nonRecuServeur ).setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel footer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_dateMessage;
    private javax.swing.JLabel lbl_nomUtilisateur;
    private javax.swing.JLabel lbl_statutMessage;
    private javax.swing.JLabel lbl_statutMessageImg;
    private javax.swing.JPanel pnl_statutMessage;
    private javax.swing.JTextArea txt_dataMessage;
    // End of variables declaration//GEN-END:variables
}
